[package]
name = "technical-task"
version = "0.1.0"
authors = ["Evsyukov Denis <denis@evsyukov.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
